import './globals.css'
import { Inter } from 'next/font/google'
import CartProvider from './store/CartProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Saints emarket',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <CartProvider>
        <body className={inter.className}>{children}</body>
      </CartProvider>
    </html>
  )
}
